#!/usr/bin/env bash

echo "Installing Neovim"

echo "v0.10.1 will be installed"
git clone -b v0.10.1 https://github.com/neovim/neovim.git $HOME/personal/neovim

echo "Installing build dependencies"
sudo apt install cmake gettext lua5.1 liblua5.1-0-dev

echo "Building neovim"
cd $HOME/personal/neovim
make CMAKE_BUILD_TYPE=RelWithDebInfo
sudo make install

echo "Installed Neovim"

echo "Configuring Neovim"
rm -rfs ~/.config/nvim #remove the default config
cp -r $0/config/nvim ~/.config/. #add config

